# Generated by Django 3.2 on 2023-05-15 21:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import reviews.validators


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0002_auto_20230516_0034"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                max_length=200, verbose_name="Название категории"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(unique=True, verbose_name="Слаг категории"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="pub_date",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                verbose_name="Дата публикации",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="review",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="reviews.review",
                verbose_name="Комментарий",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="text",
            field=models.CharField(
                max_length=200, verbose_name="Текст комментария"
            ),
        ),
        migrations.AlterField(
            model_name="genre",
            name="name",
            field=models.CharField(
                max_length=50, verbose_name="Название жанра"
            ),
        ),
        migrations.AlterField(
            model_name="genre",
            name="slug",
            field=models.SlugField(unique=True, verbose_name="Слаг жанра"),
        ),
        migrations.AlterField(
            model_name="review",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="pub_date",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                verbose_name="Дата публикации",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="score",
            field=models.IntegerField(
                error_messages={"validators": "Рейтинг не может быть выше 10"},
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ],
                verbose_name="Рейтинг",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="title",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="reviews.title",
                verbose_name="Отзыв",
            ),
        ),
        migrations.AlterField(
            model_name="title",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="titles",
                to="reviews.category",
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="title",
            name="description",
            field=models.TextField(
                blank=True, max_length=255, null=True, verbose_name="Описание"
            ),
        ),
        migrations.AlterField(
            model_name="title",
            name="genre",
            field=models.ManyToManyField(
                related_name="titles", to="reviews.Genre", verbose_name="Жанр"
            ),
        ),
        migrations.AlterField(
            model_name="title",
            name="name",
            field=models.CharField(
                db_index=True, max_length=50, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="title",
            name="year",
            field=models.IntegerField(
                validators=[reviews.validators.validate_year],
                verbose_name="Год",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="bio",
            field=models.TextField(
                blank=True, verbose_name="Персональная информация"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="confirmation_code",
            field=models.CharField(
                default="XXX",
                max_length=255,
                null=True,
                verbose_name="Код подтверждения",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="first name"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="last name"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("user", "user"),
                    ("admin", "admin"),
                    ("moderator", "moderator"),
                ],
                default="user",
                max_length=20,
                verbose_name="Роль",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                max_length=20,
                unique=True,
                validators=[reviews.validators.validate_username],
            ),
        ),
    ]
